### PR TITLE
Firebase Auth

### PR DESCRIPTION
**Pull request by Maigard**
Firebase authentication with facebook and twitter auth.
I made up a simple session object that includes the authentication. If you want to use a ember plugin to do session management, we can. In the meantime, this works.

### CODE REVIEW

**Comment by Samsinite** [comment]
Sorry just got to looking at this. It is out of sync and needs rebased with master before it can be merged

**Comment by Samsinite** [comment]
@Maigard If you would like me to rebase it and get in sync let me know.

**Comment by Maigard** [comment]
@Samsinite Yes please do. I don't think I am going to have time this weekend to do it.

**Comment by Samsinite** [comment]
I'll get this rebased and merged tonight, I have not forgotten.

**Pull request merged**
